#!/usr/bin/env python3
"""
Fetch GitHub Trending repositories and update README.md
"""
import requests
from datetime import datetime
from bs4 import BeautifulSoup

def get_trending_repos(language='', time_range='daily'):
    """Fetch GitHub Trending repositories"""
    url = f"https://github.com/trending?since={time_range}"
    if language:
        url += f"&spoken_language_code="
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    repos = []
    articles = soup.find_all('article', className='Box-row')
    
    for article in articles[:30]:  # Get top 30
        try:
            # Get repo name and URL
            repo_link = article.find('a', href=True)
            if not repo_link:
                continue
            repo_name = repo_link.get('href', '').strip('/')
            
            # Get description
            desc_tag = article.find('p')
            description = desc_tag.get_text().strip() if desc_tag else 'No description'
            
            # Get stars
            star_link = article.find('a', href=True, string=lambda t: t and 'stars' in t.lower())
            stars = star_link.get_text().strip() if star_link else '0'
            
            # Get language
            lang_tag = article.find('span', itemprop='programmingLanguage')
            lang = lang_tag.get_text().strip() if lang_tag else 'Unknown'
            
            repos.append({
                'name': repo_name,
                'description': description,
                'stars': stars,
                'language': lang,
                'url': f"https://github.com/{repo_name}"
            })
        except Exception as e:
            continue
    
    return repos

def generate_readme(repos):
    """Generate README content"""
    today = datetime.now().strftime("%Y-%m-%d")
    
    content = f"""# GitHub Hot Daily

> 每日 GitHub 热门项目汇总 | Updated: {today}

## 🔥 Trending Today

| # | Project | Description | Stars | Language |
|---|---------|-------------|-------|----------|
"""
    
    for i, repo in enumerate(repos, 1):
        desc = repo['description'][:60] + '...' if len(repo['description']) > 60 else repo['description']
        content += f"| {i} | [{repo['name']}]({repo['url']}) | {desc} | {repo['stars']} | {repo['language']} |\n"
    
    content += f"""
---

🤖 Auto-generated by [GitHub Actions](https://github.com/Evanvelyn/github-hot-daily/actions)

"""
    return content

def main():
    print("Fetching GitHub Trending...")
    repos = get_trending_repos()
    
    if not repos:
        print("Failed to fetch trending repos")
        return
    
    print(f"Found {len(repos)} repos")
    
    readme_content = generate_readme(repos)
    
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    print("README.md updated!")

if __name__ == '__main__':
    main()
