#!/usr/bin/env python3
"""
Fetch GitHub Trending repositories using GitHub API
"""
import requests
from datetime import datetime
import os

def get_trending_repos():
    """Fetch GitHub trending repos via search API"""
    url = "https://api.github.com/search/repositories"
    params = {
        'q': 'created:>2026-02-15',  # Recent repos
        'sort': 'stars',
        'order': 'desc',
        'per_page': 30
    }
    
    headers = {
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'GitHub-Trending-Bot'
    }
    
    response = requests.get(url, params=params, headers=headers)
    
    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        print(response.text)
        return []
    
    data = response.json()
    repos = []
    
    for item in data.get('items', []):
        repos.append({
            'name': item['full_name'],
            'description': item['description'] or 'No description',
            'stars': f"{item['stargazers_count']:,}",
            'language': item['language'] or 'Unknown',
            'url': item['html_url']
        })
    
    return repos

def generate_readme(repos):
    """Generate README content"""
    today = datetime.now().strftime("%Y-%m-%d")
    
    content = f"""# GitHub Hot Daily

> 每日 GitHub 热门项目汇总 | Updated: {today}

## 🔥 Trending Today

| # | Project | Description | Stars | Language |
|---|---------|-------------|-------|----------|
"""
    
    for i, repo in enumerate(repos, 1):
        desc = repo['description'][:60] + '...' if len(repo['description']) > 60 else repo['description']
        content += f"| {i} | [{repo['name']}]({repo['url']}) | {desc} | {repo['stars']} | {repo['language']} |\n"
    
    content += f"""
---

🤖 Auto-generated by [GitHub Actions](https://github.com/Evanvelyn/github-hot-daily/actions)

"""
    return content

def main():
    print("Fetching GitHub Trending...")
    repos = get_trending_repos()
    
    if not repos:
        print("Failed to fetch trending repos")
        # Create a placeholder README
        repos = [{
            'name': 'No data',
            'description': 'Failed to fetch data',
            'stars': '0',
            'language': 'N/A',
            'url': '#'
        }]
    
    print(f"Found {len(repos)} repos")
    
    readme_content = generate_readme(repos)
    
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    print("README.md updated!")

if __name__ == '__main__':
    main()
