#!/usr/bin/env python3
"""
Fetch GitHub Trending repositories using GitHub API
Saves each day as a separate file
"""
import requests
from datetime import datetime
import os

def get_trending_repos():
    """Fetch GitHub trending repos via search API"""
    url = "https://api.github.com/search/repositories"
    params = {
        'q': 'created:>2026-02-15',
        'sort': 'stars',
        'order': 'desc',
        'per_page': 30
    }
    
    headers = {
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'GitHub-Trending-Bot'
    }
    
    response = requests.get(url, params=params, headers=headers)
    
    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        print(response.text)
        return []
    
    data = response.json()
    repos = []
    
    for item in data.get('items', []):
        repos.append({
            'name': item['full_name'],
            'description': item['description'] or 'No description',
            'stars': f"{item['stargazers_count']:,}",
            'language': item['language'] or 'Unknown',
            'url': item['html_url']
        })
    
    return repos

def generate_daily_file(repos, date_str):
    """Generate a daily markdown file"""
    content = f"# GitHub Trending - {date_str}\n\n"
    content += "| # | Project | Description | Stars | Language |\n"
    content += "|---|---------|-------------|-------|----------|\n"
    
    for i, repo in enumerate(repos, 1):
        desc = repo['description'][:60] + '...' if len(repo['description']) > 60 else repo['description']
        content += f"| {i} | [{repo['name']}]({repo['url']}) | {desc} | {repo['stars']} | {repo['language']} |\n"
    
    return content

def generate_index(dates):
    """Generate README index linking to all daily files"""
    content = """# GitHub Hot Daily

> 每日 GitHub 热门项目汇总

## 📅 历史记录

"""
    for date in sorted(dates, reverse=True):
        content += f"- [{date}](daily/{date}.md)\n"
    
    content += """
---

🤖 Auto-generated by [GitHub Actions](https://github.com/Evanvelyn/github-hot-daily/actions)
"""
    return content

def main():
    today = datetime.now().strftime("%Y-%m-%d")
    daily_dir = "daily"
    
    print("Fetching GitHub Trending...")
    repos = get_trending_repos()
    
    if not repos:
        print("Failed to fetch trending repos")
        return
    
    print(f"Found {len(repos)} repos")
    
    # Create daily directory
    os.makedirs(daily_dir, exist_ok=True)
    
    # Save today's file
    daily_file = f"{daily_dir}/{today}.md"
    daily_content = generate_daily_file(repos, today)
    with open(daily_file, 'w', encoding='utf-8') as f:
        f.write(daily_content)
    
    print(f"Saved to {daily_file}")
    
    # Update README index
    existing_dates = []
    if os.path.exists(daily_dir):
        for f in os.listdir(daily_dir):
            if f.endswith('.md'):
                existing_dates.append(f.replace('.md', ''))
    
    # Add today if not already
    if today not in existing_dates:
        existing_dates.append(today)
    
    readme_content = generate_index(existing_dates)
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    print("README.md updated!")

if __name__ == '__main__':
    main()
